name: PR Update

on:
  pull_request:
    types: [labeled]
  pull_request_target:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Detect changes
    runs-on: buildjet-2vcpu-ubuntu-2204
    permissions:
      pull-requests: read
    outputs:
      has-files-requiring-all-checks: ${{ steps.filter.outputs.has-files-requiring-all-checks }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dangerous-git-checkout
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            has-files-requiring-all-checks:
              - "!(**.md|.github/CODEOWNERS)"
  type-check:
    name: Type check
    needs: [changes]
    if: ${{ needs.changes.outputs.has-files-requiring-all-checks == 'true' }}
    uses: ./.github/workflows/check-types.yml
    secrets: inherit

  lint:
    name: Linters
    needs: [changes]
    if: ${{ needs.changes.outputs.has-files-requiring-all-checks == 'true' }}
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  unit-test:
    name: Tests
    needs: [changes]
    if: ${{ needs.changes.outputs.has-files-requiring-all-checks == 'true' }}
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit

  integration-test:
    name: Tests
    needs: [changes]
    if: ${{ needs.changes.outputs.has-files-requiring-all-checks == 'true' }}
    uses: ./.github/workflows/integration-tests.yml
    secrets: inherit

  build-api-v1:
    name: Production builds
    if: contains(github.event.pull_request.labels.*.name, 'ready-for-e2e')
    uses: ./.github/workflows/api-v1-production-build.yml
    secrets: inherit

  build-api-v2:
    name: Production builds
    if: contains(github.event.pull_request.labels.*.name, 'ready-for-e2e')
    uses: ./.github/workflows/api-v2-production-build.yml
    secrets: inherit

  build:
    name: Production builds
    if: contains(github.event.pull_request.labels.*.name, 'ready-for-e2e')
    uses: ./.github/workflows/production-build-without-database.yml
    secrets: inherit

  e2e:
    name: Tests
    needs: [lint, build, build-api-v1, build-api-v2]
    if: contains(github.event.pull_request.labels.*.name, 'ready-for-e2e')
    uses: ./.github/workflows/e2e.yml
    secrets: inherit

  e2e-app-store:
    name: Tests
    needs: [lint, build, build-api-v1, build-api-v2]
    if: contains(github.event.pull_request.labels.*.name, 'ready-for-e2e')
    uses: ./.github/workflows/e2e-app-store.yml
    secrets: inherit

  e2e-embed:
    name: Tests
    needs: [lint, build, build-api-v1, build-api-v2]
    if: contains(github.event.pull_request.labels.*.name, 'ready-for-e2e')
    uses: ./.github/workflows/e2e-embed.yml
    secrets: inherit

  e2e-embed-react:
    name: Tests
    needs: [lint, build, build-api-v1, build-api-v2]
    if: contains(github.event.pull_request.labels.*.name, 'ready-for-e2e')
    uses: ./.github/workflows/e2e-embed-react.yml
    secrets: inherit

  analyze:
    name: Analyze Build
    needs: [build]
    if: contains(github.event.pull_request.labels.*.name, 'ready-for-e2e')
    uses: ./.github/workflows/nextjs-bundle-analysis.yml
    secrets: inherit

  required:
    needs: [lint, type-check, unit-test, integration-test, build, build-api-v1, build-api-v2, e2e, e2e-embed, e2e-embed-react, e2e-app-store]
    if: always()
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - name: fail if conditional jobs failed
        if: needs.changes.outputs.has-files-requiring-all-checks == 'true' && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled') || !contains(github.event.pull_request.labels.*.name, 'ready-for-e2e'))
        run: exit 1
