name: All checks

on:
  pull_request_target:
    types: [labeled]
    branches:
        - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-label:
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - name: Check for label
        id: yarn-config
        shell: bash
        run: |
          if [[ "${{ github.event.label.name }}" == "ready-for-e2e" ]]; then
            echo "::set-output name=run-jobs::true"
          else
            echo "::set-output name=run-jobs::false"
          fi
  build-api-v1:
    name: Production builds
    needs: [check-label]
    if: ${{ needs.check-label.outputs.run-jobs == 'true' }}
    uses: ./.github/workflows/api-v1-production-build.yml
    secrets: inherit

  build-api-v2:
    name: Production builds
    needs: [check-label]
    if: ${{ needs.check-label.outputs.run-jobs == 'true' }}
    uses: ./.github/workflows/api-v2-production-build.yml
    secrets: inherit

  build:
    name: Production builds
    needs: [check-label]
    if: ${{ needs.check-label.outputs.run-jobs == 'true' }}
    uses: ./.github/workflows/production-build-without-database.yml
    secrets: inherit

  e2e:
    name: Tests
    needs: [check-label, build, build-api-v1, build-api-v2]
    if: ${{ needs.check-label.outputs.run-jobs == 'true' }}
    uses: ./.github/workflows/e2e.yml
    secrets: inherit

  e2e-app-store:
    name: Tests
    needs: [check-label, build, build-api-v1, build-api-v2]
    if: ${{ needs.check-label.outputs.run-jobs == 'true' }}
    uses: ./.github/workflows/e2e-app-store.yml
    secrets: inherit

  e2e-embed:
    name: Tests
    needs: [check-label, build, build-api-v1, build-api-v2]
    if: ${{ needs.check-label.outputs.run-jobs == 'true' }}
    uses: ./.github/workflows/e2e-embed.yml
    secrets: inherit

  e2e-embed-react:
    name: Tests
    needs: [check-label, build, build-api-v1, build-api-v2]
    if: ${{ needs.check-label.outputs.run-jobs == 'true' }}
    uses: ./.github/workflows/e2e-embed-react.yml
    secrets: inherit

  analyze:
    name: Analyze Build
    needs: [build]
    uses: ./.github/workflows/nextjs-bundle-analysis.yml
    secrets: inherit

  e2e-required:
    needs: [check-label, build, build-api-v1, build-api-v2, e2e, e2e-embed, e2e-embed-react, e2e-app-store]
    if: always()
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - name: fail if conditional jobs failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled') || !contains(github.event.pull_request.labels.*.name, 'ready-for-e2e')
        run: exit 1
